// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #AdbInput is the `adb` verb's plugin_input: the method name plus its
// method-exclusive modifiers.
type AdbInput struct {
	// method — the adb method name (the former core #AdbMethod enum; the verb's
	// PRIMARY input field, so `adb: devices` desugars to {method: "devices"}).
	Method string `yaml:"method,omitempty" json:"method"`

	// arg — the shell argv (shell: arg[0] program + arg[1:] args) / the package id
	// (uninstall: arg[0]).
	Args []string `yaml:"arg,omitempty" json:"arg,omitempty"`

	// apk — HOST path of a committed APK (install); resolved to an absolute
	// candy-anchored path by the host before marshaling.
	Apk string `yaml:"apk,omitempty" json:"apk,omitempty"`

	// app_id / source / arch / app_version — the apkeep package spec (install-app).
	AppId string `yaml:"app_id,omitempty" json:"app_id,omitempty"`

	Source string `yaml:"source,omitempty" json:"source,omitempty"`

	Arch string `yaml:"arch,omitempty" json:"arch,omitempty"`

	AppVersion string `yaml:"app_version,omitempty" json:"app_version,omitempty"`

	// property — the system property key (getprop), e.g. sys.boot_completed.
	Property string `yaml:"property,omitempty" json:"property,omitempty"`

	// key — the key event to send (keyevent), e.g. KEYCODE_HOME or a numeric code.
	KeyName string `yaml:"key,omitempty" json:"key,omitempty"`

	// query / amount — the literal logcat filter spec + last-N-lines trim (logcat-tail).
	Query string `yaml:"query,omitempty" json:"query,omitempty"`

	Amount int `yaml:"amount,omitempty" json:"amount,omitempty"`

	// artifact + validators — screencap's PNG output path and the post-run
	// artifact-reality assertions (sdk.RunArtifactValidators reads them off the input).
	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	ArtifactMinBytes int `yaml:"artifact_min_bytes,omitempty" json:"artifact_min_bytes,omitempty"`

	ArtifactMinDimensions string `yaml:"artifact_min_dimensions,omitempty" json:"artifact_min_dimensions,omitempty"`

	ArtifactNotUniform bool `yaml:"artifact_not_uniform,omitempty" json:"artifact_not_uniform,omitempty"`

	ArtifactMinCastEvents int `yaml:"artifact_min_cast_events,omitempty" json:"artifact_min_cast_events,omitempty"`

	// session + session lifecycle — the ON-DEVICE screenrecord bracket (plan
	// Cutover E, E-4): `adb: session` runs the plugin's OWN binary in recorder mode
	// through the runner's generic background-session service (plugin-check's
	// verb:session seam). start launches the device-side `screenrecord` detached
	// (nohup screenrecord --time-limit 1800 /sdcard/<session_id>.mp4 &), stop
	// SIGINTs it (pkill -INT) and pulls the finalized MP4 via the goadb
	// device-file GetFile path (OpenRead — the same sync wire the committed-APK
	// push uses) into state_dir/<session_id>.mp4, then finalizes with the FINAL
	// marker + the evidence row.json (the shared #EvidenceRow shape). The provider
	// holds no device wire for a session — the detached recorder does.
	Action string `yaml:"action,omitempty" json:"action,omitempty"`

	SessionId string `yaml:"session_id,omitempty" json:"session_id,omitempty"`

	StateDir string `yaml:"state_dir,omitempty" json:"state_dir,omitempty"`

	// artifact_dir — the runner-injected generic evidence-artifact dir (verb-agnostic;
	// the provider appends its own filename/extension).
	ArtifactDir string `yaml:"artifact_dir,omitempty" json:"artifact_dir,omitempty"`

	LogDir string `yaml:"log_dir,omitempty" json:"log_dir,omitempty"`

	Venue string `yaml:"venue,omitempty" json:"venue,omitempty"`

	Phase string `yaml:"phase,omitempty" json:"phase,omitempty"`
}
