// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #AdbInput is the `adb` verb's plugin_input: the method name plus its
// method-exclusive modifiers.
type AdbInput struct {
	// method — the adb method name (the former core #AdbMethod enum; the verb's
	// PRIMARY input field, so `adb: devices` desugars to {method: "devices"}).
	Method string `yaml:"method,omitempty" json:"method"`

	// arg — the shell argv (shell: arg[0] program + arg[1:] args) / the package id
	// (uninstall: arg[0]).
	Args []string `yaml:"arg,omitempty" json:"arg,omitempty"`

	// apk — HOST path of a committed APK (install); resolved to an absolute
	// candy-anchored path by the host before marshaling.
	Apk string `yaml:"apk,omitempty" json:"apk,omitempty"`

	// app_id / source / arch / app_version — the apkeep package spec (install-app).
	AppId string `yaml:"app_id,omitempty" json:"app_id,omitempty"`

	Source string `yaml:"source,omitempty" json:"source,omitempty"`

	Arch string `yaml:"arch,omitempty" json:"arch,omitempty"`

	AppVersion string `yaml:"app_version,omitempty" json:"app_version,omitempty"`

	// property — the system property key (getprop), e.g. sys.boot_completed.
	Property string `yaml:"property,omitempty" json:"property,omitempty"`

	// key — the key event to send (keyevent), e.g. KEYCODE_HOME or a numeric code.
	KeyName string `yaml:"key,omitempty" json:"key,omitempty"`

	// query / amount — the literal logcat filter spec + last-N-lines trim (logcat-tail).
	Query string `yaml:"query,omitempty" json:"query,omitempty"`

	Amount int `yaml:"amount,omitempty" json:"amount,omitempty"`

	// artifact + validators — screencap's PNG output path and the post-run
	// artifact-reality assertions (sdk.RunArtifactValidators reads them off the input).
	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	ArtifactMinBytes int `yaml:"artifact_min_bytes,omitempty" json:"artifact_min_bytes,omitempty"`

	ArtifactMinDimensions string `yaml:"artifact_min_dimensions,omitempty" json:"artifact_min_dimensions,omitempty"`

	ArtifactNotUniform bool `yaml:"artifact_not_uniform,omitempty" json:"artifact_not_uniform,omitempty"`

	ArtifactMinCastEvents int `yaml:"artifact_min_cast_events,omitempty" json:"artifact_min_cast_events,omitempty"`
}
